### ISSUE TITLE
Memory usage while testing

### ISSUE THREAD

**Issue by Klopotek0** [weepiess/Official-Code-for-StyleFlow-For-Content-Fixed-Image-to-Image-Translation#14]
Hi I used your approach to train my dataset. Results look promising but, I have a problem with testing. The model uses ridiculus amount of memory:
`
=> loaded checkpoint '/content/StyleFlow-Content-Fixed-I2I/scripts/output/wikiart_tv_loss_0.6/model_save/3000.ckpt.pth.tar'
Traceback (most recent call last):
  File "/content/StyleFlow-Content-Fixed-I2I/test.py", line 101, in <module>
    main()
  File "/content/StyleFlow-Content-Fixed-I2I/test.py", line 95, in main
    stylized = model(imgA.cuda(),domain_class=base_code.cuda())
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/StyleFlow-Content-Fixed-I2I/model/trainers/Trainer_StyleFlow.py", line 33, in forward
    stylized = self.glow(z_c, forward=False, style=domain_class)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/StyleFlow-Content-Fixed-I2I/model/network/glow.py", line 145, in forward
    return self._reverse_set(input, style=style)
  File "/content/StyleFlow-Content-Fixed-I2I/model/network/glow.py", line 156, in _reverse_set
    out = block.reverse(out,style)
  File "/content/StyleFlow-Content-Fixed-I2I/model/network/glow.py", line 115, in reverse
    input = flow.reverse(input)
  File "/content/StyleFlow-Content-Fixed-I2I/model/network/glow.py", line 81, in reverse
    input = self.coupling.reverse(input)
  File "/content/StyleFlow-Content-Fixed-I2I/model/network/glow.py", line 51, in reverse
    net_out = self.net(out_a)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 60.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 46.81 MiB is free. Process 5955 has 358.00 MiB memory in use. Process 630649 has 14.35 GiB memory in use. Of the allocated memory 12.86 GiB is allocated by PyTorch, and 322.92 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CON`

During training I had no problems but now is is ridiculusly high. How to fix the issue?
I need to let model through my dataset and save them. Anyway, how much memory is needed to test model performance? Images resized for training to 300x400. Didn't change anything for test. 16gb cars is also not enough.

**Comment by WeichenFan** [comment]
Hi, thanks for your interest. It is quite weird since our model is trained and tested on a single GTX 1080ti 11G. Maybe u could try to put the encoder on the CPU (https://github.com/weepiess/StyleFlow-Content-Fixed-I2I/blob/master/test.py#L87), and move the base_code to cuda then, cuz VGG network could take up some memory. BTW, how many "n_flow" and "n_block" are you using right now?

**Comment by Klopotek0** [comment]
I used 15 "n_flow" and 2 "n_block", just like in default wiki_06 config.

I moved all test code to cpu (Im working on collab so I have plenty of RAM), and I'm capable of evaluating images. Worth noting that memory usage is up to 20gb (!). 

Oh I also notcied that photos tested are not 100% same, they do seem to have a little bit of stretch added to them. Like artifical zoom in, which makes then not match exactly same (shape is still same, but zoom is apparent)

Why is that? I had to have them exactly same shape I need them for segmentation purposes.

Also I don't really need to use image target image to convert to another image. I just want to "tranfer the style" from one to another without reference point. I see that test.py uses another image as reference. What would be the setting to test it "GTA" like?

**Comment by Klopotek0** [comment]
I moved all test code to cpu (Im working on collab so I have plenty of RAM), and I'm capable of evaluating images. Worth noting that memory usage is up to 20gb (!). Worth troubleshooting. I also resized images down to 256x256.

**Comment by WeichenFan** [comment]
1. About the huge mem costs, I’ll further investigate this issue during the weekend, stay tuned.
2. What do you mean by “not exactly the same”, the img should be resized to a fixed size for inference.
3. You do need a target img to calculate the reference base_code.

**Comment by Klopotek0** [comment]
Thanks, for reply. Regarding 2. I will just send you the link to side by side photos on imgur. 
https://imgur.com/a/fyL7ICy
It's maybe hard to notice at first, but the images get "zoomed in". Cropped and resized to given size is how I would describe it.  Blurry ones are the source ones, and the lighter are straight out of the model evaluation. If you take them side by side you will see it in no time. 400x300 img resolution used for train and test .
This stuff is really important to me because I have segmenatation masks done on source data, and even this small variances can affect my work.


Okay, dataset.py, just needed to comment out RandomResiedCrop(300.400). Made it misleading though since it's train_vr loop makes it look used only for training. Anyway, mem usage is the only problem.

Worth noting that I'm using up-to date packages.

**Comment by Klopotek0** [comment]
Okay, dataset.py, just needed to comment out RandomResiedCrop(300.400). Made it misleading though since it's train_vr loop makes it look used only for training. Anyway.

**Comment by Klopotek0** [comment]
Regarding 3. But that's for image-guided transformation. How to perform sampling-based?
